services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  portier:
    image: portier/broker:latest
    container_name: portier
    ports:
      - 3333:3333
    environment:
      - BROKER_FROM_NAME=Portier
      - BROKER_FROM_ADDRESS=login@example.com
      - BROKER_PUBLIC_URL=http://127.0.0.1:3333
      - BROKER_SMTP_SERVER=mailcrab:1025
    command: ["/data/config.toml"]
    volumes:
      - ./conf/portier:/tmp/templates
      - ./conf/portier.toml:/data/config.toml

  mailcrab:
    image: marlonb/mailcrab:latest
    container_name: mailcrab
    ports:
      - 1080:1080
      - 1025:1025 

volumes:
  redis_data:
